[build]
  # publish = "build"        # for Create React App
  publish = "dist"       # for Vite or other tools
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200